### ISSUE TITLE
Updating to weewx 5.0.1

### ISSUE THREAD

**Issue by ruimarinho** [Daveiano/weewx-wdc-interceptor-docker#3]
Hi!

Do you plan on updating the image to [weewx 5.0.1](https://weewx.com/docs/5.0/changes/#501-mmddyyyy)?

Thanks.

**Comment by Daveiano** [comment]
Hello there, yes an update to WeeWX v5 will arriving soon! I hope within the next week, sorry I am a bit busy currently.

**Comment by Daveiano** [comment]
The `main` branch and all other branches are using WeeWX v5.0.2 now!
